### ISSUE TITLE
ModeNotFoundError : No module named 'cloudscraper'

### ISSUE THREAD

**Issue by axcnee** [Geekeh/bloxflip-auto-mines#1]
Hello, Geekeh.

I encountered this error whilst after installing the module you told me to install anyway to fix it? thanks. also, wonderful code and thanks for making it public.

**Comment by Breetelitify** [comment]
Go to command prompt, then type "pip install cloudscraper" If you need any more questions just go to their server | [https://discord.gg/juicy](https://discord.gg/juicy)
