### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Xeto2W** [Geekeh/bloxflip-auto-mines#2]
Can U help?

![Screenshot_20221027-095555_Chrome](https://user-images.githubusercontent.com/108171547/198212729-3c6e3ab9-941b-4e80-b12d-bff66674e38a.jpg)

**Comment by accusable** [comment]
error w the bloxflip lib

**Comment by fmkash** [comment]
Hey there, replit hosting does not work with this command. You will need to host it locally.
